# -*- coding: utf-8 -*-
"""cv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_FoM5wrJ2ga8DtwG6hoJeWx24ihuCgM
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="eqRHytfit0z45aSiBoB7")
project = rf.workspace("project-uyrxf").project("ppe_detection-v1x3l")
version = project.version(2)
dataset = version.download("yolov8")

!pip install ultralytics

from ultralytics import YOLO
import os
from IPython.display import display,Image
from IPython import display
display.clear_output()
!yolo checks

!yolo detect train model=yolov8n.pt data=/content/PPE_Detection-2/data.yaml epochs=20 imgsz=640

!yolo detect train model=yolov8n.pt data=/content/PPE_Detection-2/data.yaml epochs=20 imgsz=640

from IPython.display import Image
Image(filename = '/content/runs/detect/train2/F1_curve.png')
Image(filename = '/content/runs/detect/train2/PR_curve.png')
Image(filename = '/content/runs/detect/train2/P_curve.png')
Image(filename = '/content/runs/detect/train2/R_curve.png')
Image(filename = '/content/runs/detect/train2/confusion_matrix_normalized.png')
Image(filename = '/content/runs/detect/train2/labels.jpg')
Image(filename = '/content/runs/detect/train2/results.png')



!yolo detect val model=/content/runs/detect/train2/weights/best.pt data=/content/PPE_Detection-2/data.yaml epochs=20 imgsz=640

from IPython.display import Image
Image(filename = '/content/runs/detect/val/F1_curve.png')
Image(filename = '/content/runs/detect/val/PR_curve.png')
Image(filename = '/content/runs/detect/val/P_curve.png')
Image(filename = '/content/runs/detect/val/R_curve.png')
Image(filename = '/content/runs/detect/val/confusion_matrix.png')
Image(filename = '/content/runs/detect/val/confusion_matrix_normalized.png')
Image(filename = '/content/runs/detect/val/val_batch2_pred.jpg')

Image(filename = '/content/runs/detect/val/F1_curve.png')

Image(filename = '/content/runs/detect/val/F1_curve.png')

Image(filename = '/content/runs/detect/val/PR_curve.png')

Image(filename = '/content/runs/detect/val/P_curve.png')

Image(filename = '/content/runs/detect/val/R_curve.png')

Image(filename = '/content/runs/detect/val/confusion_matrix.png')

Image(filename = '/content/runs/detect/val/confusion_matrix_normalized.png')

